name: Run Task2 Advanced

on:
  workflow_dispatch:
  push:
    paths:
      - 'Task2_Advanced/**'

jobs:
  run-advanced:
    runs-on: ubuntu-latest

    services:
      otel-collector:
        image: otel/opentelemetry-collector:latest
        ports:
          - 4317:4317
          - 4318:4318
        # Montamos tu config y carpeta de salida
        volumes:
          - ${{ github.workspace }}/Task2_Advanced/otel-collector-config.yaml:/etc/otelcol/config.yaml
          - ${{ github.workspace }}/Task2_Advanced:/var/otel
        options: --name otel-collector

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Collector to be ready
        run: |
          echo "Esperando 10 segundos a que el collector arranque..."
          sleep 10
          docker ps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r Task2_Advanced/requirement_


