name: Run Task2 Advanced

on:
  workflow_dispatch:
  push:
    paths:
      - 'Task2_Advanced/**'

jobs:
  run-advanced:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start OpenTelemetry Collector (background)
        run: |
          docker run -d --name otel-collector \
            -v ${{ github.workspace }}/Task2_Advanced/otel-collector-config.yaml:/etc/otelcol/config.yaml \
            -p 4317:4317 -p 4318:4318 \
            otel/opentelemetry-collector:latest
          echo "Esperando 10 segundos..."
          sleep 10
          docker ps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r Task2_Advanced/requirements.txt

      - name: Send traces to Collector (OTLP gRPC)
        run: python Task2_Advanced/app_sender.py

      - name: Show collector logs (should include spans)
        run: |
          echo "=== Collector stdout (logging exporter) ==="
          docker logs otel-collector --tail=500

      - name: Stop and remove Collector
        if: always()
        run: docker rm -f otel-collector || true





