name: Run Task3 Outstanding

on:
  workflow_dispatch:
  push:
    paths:
      - 'Task3_Outstanding/**'

jobs:
  run-outstanding:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start OpenTelemetry Collector (background)
        run: |
          docker run -d --name otel-collector \
            -v ${{ github.workspace }}/Task3_Outstanding/otel-collector-config.yaml:/etc/otelcol/config.yaml \
            -p 4317:4317 -p 4318:4318 \
            otel/opentelemetry-collector:latest
          echo "Esperando 10 segundos..."
          sleep 10
          docker ps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r Task3_Outstanding/requirements.txt

      - name: Run app (send traces and logs)
        run: python Task3_Outstanding/app_flask.py

      - name: Show collector logs (traces + logs)
        run: |
          echo "=== Collector stdout (debug exporter) ==="
          docker logs otel-collector --tail=500

      - name: Stop and remove Collector
        if: always()
        run: docker rm -f otel-collector || true
