name: Run Task2 Advanced

on:
  workflow_dispatch:
  push:
    paths:
      - 'Task2_Advanced/**'

jobs:
  run-advanced:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start OpenTelemetry Collector (background)
        run: |
          docker run -d --name otel-collector \
            -v ${{ github.workspace }}/Task2_Advanced/otel-collector-config.yaml:/etc/otelcol/config.yaml \
            -v ${{ github.workspace }}/Task2_Advanced:/var/otel \
            -p 4317:4317 -p 4318:4318 \
            otel/opentelemetry-collector:latest
          echo "Esperando 10 segundos..."
          sleep 10
          docker ps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r Task2_Advanced/requirements.txt

      - name: Send traces to Collector (OTLP gRPC)
        run: python Task2_Advanced/app_sender.py

      - name: Wait and extract traces.json from container
        run: |
          echo "Esperando al Collector para terminar escritura..."
          sleep 5
          docker cp otel-collector:/var/otel/traces.json Task2_Advanced/traces.json || echo "No se pudo copiar traces.json"
          echo "Vista previa de traces.json:"
          cat Task2_Advanced/traces.json || echo "❌ No existe el archivo aún"

      - name: Upload traces.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: task2-traces
          path: Task2_Advanced/traces._




